[tool.poetry]
name = "multi_error"
version = "0.1.0"
description = ""
authors = ["John Freeman <jfreeman08@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
async_generator = "^1.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.5"
mypy = "^0.630.0"
